### ISSUE TITLE
50% performance loss with SDL 2.0.8

### ISSUE THREAD

**Issue by lotharsm** [mgba-emu/dependencies#2]
After updating my MSYS2/Mingw-w64 environment to SDL 2.0.8, I noticed a performance loss of about 50% when audio synchronization is enabled compared to previous versions of the SDL2 library.

I compared it with my own compilation of the current master code with SDL 2.0.7 and a current nightly compiled by the buildbot. It doesn't matter if I try with a GB, GBC or GBA game as I always get the same results.

SDL 2.0.7 and 2.0.5:
Audio buffer size of 1024 samples: stable 60 FPS.
Audio buffer size of 786 samples: stable 60 FPS.
Audio buffer size of 512 samples: stable 60 FPS.
Audio buffer size of 384 samples: around 52 FPS.

SDL 2.0.8:
Audio buffer size of 1024 samples: stable 60 FPS.
Audio buffer size of 786 samples: around 48 FPS.
Audio buffer size of 512 samples: around 32.5 FPS.
Audio buffer size of 384 samples: around 23.5 FPS.

It is noteworthy that the performance drop clearly has something to do with the audio synchronization. If I untick audio sync in the settings, FPS for both versions get up into several thousand FPS.

OS: Windows 10, 1709, build 16299.309
Graphics hardware: AMD Radeon RX 560D
CPU: AMD Ryzen 5 1600
Onboard audio chip.
Latest drivers for everything.

**Comment by endrift** [comment]
I've updated to 2.0.7 pending investigation.

**Comment by lotharsm** [comment]
Thanks! Let me know if you need any additional information.

**Comment by Macleykun** [comment]
Any update on this?

**Comment by endrift** [comment]
So this is clearly related to the removal of XAudio2 and substitution with WASAPI, but I don't know what exactly is causing it to hang. In the meantime I can probably get mGBA to default to using DirectSound instead, which doesn't have this problem.

**Comment by endrift** [comment]
Worked around in https://github.com/mgba-emu/mgba/commit/00b46d704121e5b19afd31719ea7d5176cfd68f1

**Comment by lotharsm** [comment]
Thanks for this fix, I'll revisit it as soon as possible.
